### PR TITLE
Simplify action validation in FilterScriptManagerServlet

### PR DESCRIPTION
**Pull request by alexpanov**

### CODE REVIEW

**Comment by NiteshKant** [comment]
@alexpanov can you rebase your branch? Thanks to @rspieldenner travis is now setup for zuul and we can see if your changes aren't breaking the build!

**Comment by alexpanov** [comment]
@NiteshKant Done

**Comment by alexpanov** [comment]
@NiteshKant 
Hi. Any updates?

**Comment by kerumai** [comment]
Apologies for the slow response on this @alexpanov . Merged now.

**Pull request merged**
