### PR TITLE
Updated httpclient and cleaned up example

### PR DESCRIPTION
**Pull request by freddd**
Hi,

I was trying out the simple example when I noticed it was using an old httpclient with quite a lot of deprecated classes. This is an updated version using httpclient 4.5 and did some cleanup for readability (though some of it was mostly to get rid of warnings).

Let me know if you want me to add/change anything.

### CODE REVIEW

**Comment by NiteshKant** [comment]
Thanks @freddd for the PR. I will review it in a couple of days & merge.

**Comment by NiteshKant** [comment]
I am waiting on the travis integration to be in place before I merge these changes as these changes are non-critical and I would like to see if there are no issues w.r.t the build.

**Comment by NiteshKant** [comment]
@freddd can you rebase your branch? Thanks to @rspieldenner travis is now setup for zuul and we can see if your changes aren't breaking the build!

**Comment by freddd** [comment]
@NiteshKant, just rebased and force pushed. Seems like travis is happy!

**Comment by NiteshKant** [comment]
Thanks @freddd

**Pull request merged**
