### PR TITLE
Add throws ZuulException to IZuulFilter.run()

### PR DESCRIPTION
**Pull request by spencergibb**
fixes gh-101

### CODE REVIEW

**Comment by Aloren** [comment]
@spencergibb I suppose that `ZuulRuntimeException` can be now removed from spring-cloud-netflix project. 👍

**Comment by SimpleDeveloper49** [comment]
Is there a date for when this PR will be merged in?

**Comment by spencergibb** [comment]
last commit on 1.x was 6+ months ago. This line is not a priority for netflix.

**Comment by mattnelson** [comment]
@twicksell @artgon @kerumai

Could we get some attention from Netflix on these open pull requests?

**Pull request merged**
